#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/tailscale-resolved-nm-health.sh"
RUNBOOK="$REPO_ROOT/docs/tailscale-resolved-nm-runbook.md"
TMPDIR_T="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_T"' EXIT

make_layout() {
    local root="$1"
    mkdir -p "$root/etc/NetworkManager/conf.d" "$root/run/systemd/resolve"
    printf 'nameserver 127.0.0.53\n' >"$root/run/systemd/resolve/stub-resolv.conf"
    printf '[main]\nplugins=keyfile\n' >"$root/etc/NetworkManager/NetworkManager.conf"
}

run_check() {
    local root="$1"
    TAILSCALE_RESOLV_CONF="$root/etc/resolv.conf" \
    TAILSCALE_STUB_RESOLV_CONF="$root/run/systemd/resolve/stub-resolv.conf" \
    TAILSCALE_NM_CONFIG_FILE="$root/etc/NetworkManager/NetworkManager.conf" \
    TAILSCALE_NM_CONFIG_DIR="$root/etc/NetworkManager/conf.d" \
    TAILSCALE_SKIP_LIVE_PROBES=1 \
        "$SCRIPT" --check
}

install_getent_mock() {
    local mockdir="$1"
    mkdir -p "$mockdir"
    cat >"$mockdir/getent" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" != "hosts" ]]; then
    exit 1
fi
case "${2:-}" in
    pixel-8|machine.tail0af98d.ts.net|github.com|cloudflare.com)
        printf '127.0.0.1 %s\n' "$2"
        ;;
    *)
        exit 2
        ;;
esac
EOF
    chmod +x "$mockdir/getent"
}

install_apply_mocks() {
    local mockdir="$1"
    mkdir -p "$mockdir"
    cat >"$mockdir/id" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "-u" ]]; then
    printf '0\n'
    exit 0
fi
exec /usr/bin/id "$@"
EOF
    chmod +x "$mockdir/id"

    cat >"$mockdir/systemctl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf 'systemctl:%s\n' "$*" >>"$TAILSCALE_APPLY_LOG"
case "$*" in
    'is-active --quiet systemd-resolved')
        [[ "${TAILSCALE_SYSTEMD_RESOLVED_ACTIVE:-0}" == "1" ]]
        ;;
    'is-enabled --quiet systemd-resolved')
        [[ "${TAILSCALE_SYSTEMD_RESOLVED_ENABLED:-0}" == "1" ]]
        ;;
    restart*)
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
EOF
    chmod +x "$mockdir/systemctl"

    cat >"$mockdir/install" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf 'install:%s\n' "$*" >>"$TAILSCALE_APPLY_LOG"
exec /usr/bin/install "$@"
EOF
    chmod +x "$mockdir/install"

    cat >"$mockdir/ln" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf 'ln:%s\n' "$*" >>"$TAILSCALE_APPLY_LOG"
exec /usr/bin/ln "$@"
EOF
    chmod +x "$mockdir/ln"
}

[[ -x "$SCRIPT" ]] || {
    echo "FAIL: tailscale resolved/NM helper must exist and be executable" >&2
    exit 1
}
bash -n "$SCRIPT"

BAD_ROOT="$TMPDIR_T/bad"
make_layout "$BAD_ROOT"
printf '# Generated by NetworkManager\nnameserver 127.0.0.53\n' >"$BAD_ROOT/etc/resolv.conf"
if run_check "$BAD_ROOT" >"$TMPDIR_T/bad.out" 2>"$TMPDIR_T/bad.err"; then
    echo "FAIL: check should fail when resolv.conf is a regular NetworkManager-owned file" >&2
    exit 1
fi
grep -q 'FAIL: .*resolv.conf is not a symlink' "$TMPDIR_T/bad.err" || {
    echo "FAIL: missing regular-file resolv.conf diagnostic" >&2
    cat "$TMPDIR_T/bad.err" >&2
    exit 1
}
grep -q 'FAIL: NetworkManager has no \[main\] dns=systemd-resolved setting' "$TMPDIR_T/bad.err" || {
    echo "FAIL: missing NetworkManager dns=systemd-resolved diagnostic" >&2
    cat "$TMPDIR_T/bad.err" >&2
    exit 1
}

GOOD_ROOT="$TMPDIR_T/good"
make_layout "$GOOD_ROOT"
ln -s "$GOOD_ROOT/run/systemd/resolve/stub-resolv.conf" "$GOOD_ROOT/etc/resolv.conf"
printf '[main]\ndns=systemd-resolved\n' >"$GOOD_ROOT/etc/NetworkManager/conf.d/90-pgu-systemd-resolved.conf"
run_check "$GOOD_ROOT" >"$TMPDIR_T/good.out" 2>"$TMPDIR_T/good.err"
grep -Eq 'OK: .*resolv.conf (points to|resolves to) .*stub-resolv.conf' "$TMPDIR_T/good.out" || {
    echo "FAIL: check did not accept the stub resolv.conf symlink" >&2
    cat "$TMPDIR_T/good.out" >&2
    cat "$TMPDIR_T/good.err" >&2
    exit 1
}
grep -q 'OK: NetworkManager \[main\] dns=systemd-resolved' "$TMPDIR_T/good.out" || {
    echo "FAIL: check did not accept NetworkManager dns=systemd-resolved" >&2
    cat "$TMPDIR_T/good.out" >&2
    exit 1
}

"$SCRIPT" --print-root-commands >"$TMPDIR_T/commands.out"
grep -q '^set -euo pipefail$' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must enforce preflight failures in an interactive shell" >&2
    exit 1
}
grep -q '/etc/NetworkManager/conf.d/90-pgu-systemd-resolved.conf' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must install the NetworkManager override" >&2
    exit 1
}
grep -q "dns=systemd-resolved" "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must set dns=systemd-resolved" >&2
    exit 1
}
grep -q 'pgu-pre-resolved-nm' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must back up a regular resolv.conf before replacing it" >&2
    exit 1
}
grep -q 'systemctl is-active --quiet systemd-resolved' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify systemd-resolved is active before changing resolv.conf" >&2
    exit 1
}
grep -q 'systemctl is-enabled --quiet systemd-resolved' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify systemd-resolved is enabled before changing resolv.conf" >&2
    exit 1
}
grep -q 'test -e /run/systemd/resolve/stub-resolv.conf' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify the resolved stub exists before changing resolv.conf" >&2
    exit 1
}
grep -q 'ln -sfn /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must point resolv.conf at resolved stub" >&2
    exit 1
}
grep -q 'systemctl restart systemd-resolved' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must restart systemd-resolved" >&2
    exit 1
}
grep -q 'systemctl restart NetworkManager' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must restart NetworkManager" >&2
    exit 1
}
grep -q 'systemctl restart tailscaled' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must restart tailscaled" >&2
    exit 1
}
grep -q 'getent hosts pixel-8' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify MagicDNS short-name lookup" >&2
    exit 1
}
if grep -q 'getent hosts example.com' "$TMPDIR_T/commands.out"; then
    echo "FAIL: printed root commands must not use example.com as the ordinary DNS canary" >&2
    exit 1
fi
grep -q 'getent hosts github.com || getent hosts cloudflare.com' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify ordinary DNS with host-resolvable controls" >&2
    exit 1
}
TAILSCALE_MAGICDNS_HOSTS="custom-tailnet-name" \
TAILSCALE_INTERNET_PROBE_HOSTS="wikipedia.org cloudflare.com" \
    "$SCRIPT" --print-root-commands >"$TMPDIR_T/override-commands.out"
grep -q 'getent hosts custom-tailnet-name' "$TMPDIR_T/override-commands.out" || {
    echo "FAIL: printed root commands must derive MagicDNS probes from TAILSCALE_MAGICDNS_HOSTS" >&2
    cat "$TMPDIR_T/override-commands.out" >&2
    exit 1
}
grep -q 'getent hosts wikipedia.org || getent hosts cloudflare.com' "$TMPDIR_T/override-commands.out" || {
    echo "FAIL: printed root commands must derive ordinary DNS probes from TAILSCALE_INTERNET_PROBE_HOSTS" >&2
    cat "$TMPDIR_T/override-commands.out" >&2
    exit 1
}
if grep -q 'getent hosts github.com' "$TMPDIR_T/override-commands.out"; then
    echo "FAIL: printed root command overrides must not retain hardcoded default ordinary DNS probes" >&2
    cat "$TMPDIR_T/override-commands.out" >&2
    exit 1
fi
grep -q 'tailscale status' "$TMPDIR_T/commands.out" || {
    echo "FAIL: printed root commands must verify Tailscale health output" >&2
    exit 1
}

grep -q 'scripts/tailscale-resolved-nm-health.sh --check' "$RUNBOOK" || {
    echo "FAIL: runbook must document the read-only health check" >&2
    exit 1
}
grep -q 'sudo scripts/tailscale-resolved-nm-health.sh --apply' "$RUNBOOK" || {
    echo "FAIL: runbook must document the supervised root apply command" >&2
    exit 1
}
grep -q '/run/systemd/resolve/stub-resolv.conf' "$RUNBOOK" || {
    echo "FAIL: runbook must document the resolved stub target" >&2
    exit 1
}
grep -q 'resolv.conf.pgu-pre-resolved-nm' "$RUNBOOK" || {
    echo "FAIL: runbook must document how to restore the resolv.conf backup on rollback" >&2
    exit 1
}
grep -q 'sudo rm -f /etc/resolv.conf; sudo cp -a "$latest_backup" /etc/resolv.conf' "$RUNBOOK" || {
    echo "FAIL: rollback must replace the symlink with the saved resolv.conf backup" >&2
    exit 1
}
if grep -q 'example.com' "$RUNBOOK"; then
    echo "FAIL: runbook must not use example.com as an acceptance criterion on this host" >&2
    exit 1
fi

MOCKDIR="$TMPDIR_T/mockbin"
install_getent_mock "$MOCKDIR"
PATH="$MOCKDIR:/usr/bin:/bin" \
TAILSCALE_MAGICDNS_HOSTS="pixel-8 machine.tail0af98d.ts.net" \
TAILSCALE_INTERNET_PROBE_HOSTS="bad-control.invalid github.com" \
TAILSCALE_SKIP_LIVE_PROBES=0 \
TAILSCALE_RESOLV_CONF="$GOOD_ROOT/etc/resolv.conf" \
TAILSCALE_STUB_RESOLV_CONF="$GOOD_ROOT/run/systemd/resolve/stub-resolv.conf" \
TAILSCALE_NM_CONFIG_FILE="$GOOD_ROOT/etc/NetworkManager/NetworkManager.conf" \
TAILSCALE_NM_CONFIG_DIR="$GOOD_ROOT/etc/NetworkManager/conf.d" \
    "$SCRIPT" --check >"$TMPDIR_T/probes.out" 2>"$TMPDIR_T/probes.err"
grep -q 'OK: ordinary DNS resolves github.com' "$TMPDIR_T/probes.out" || {
    echo "FAIL: check must report the passing ordinary DNS control" >&2
    cat "$TMPDIR_T/probes.out" >&2
    cat "$TMPDIR_T/probes.err" >&2
    exit 1
}
grep -q 'OK: ordinary DNS has a passing control; inconclusive failed controls: bad-control.invalid' "$TMPDIR_T/probes.out" || {
    echo "FAIL: one failed ordinary DNS control should be inconclusive when another control passes" >&2
    cat "$TMPDIR_T/probes.out" >&2
    cat "$TMPDIR_T/probes.err" >&2
    exit 1
}
if grep -q 'WARN: DNS probe failed for bad-control.invalid' "$TMPDIR_T/probes.err"; then
    echo "FAIL: a single failed ordinary DNS control must not warn when another control passes" >&2
    exit 1
fi
PATH="$MOCKDIR:/usr/bin:/bin" \
TAILSCALE_MAGICDNS_HOSTS="pixel-8 machine.tail0af98d.ts.net" \
TAILSCALE_INTERNET_PROBE_HOSTS="bad-one.invalid bad-two.invalid" \
TAILSCALE_SKIP_LIVE_PROBES=0 \
TAILSCALE_RESOLV_CONF="$GOOD_ROOT/etc/resolv.conf" \
TAILSCALE_STUB_RESOLV_CONF="$GOOD_ROOT/run/systemd/resolve/stub-resolv.conf" \
TAILSCALE_NM_CONFIG_FILE="$GOOD_ROOT/etc/NetworkManager/NetworkManager.conf" \
TAILSCALE_NM_CONFIG_DIR="$GOOD_ROOT/etc/NetworkManager/conf.d" \
    "$SCRIPT" --check >"$TMPDIR_T/all-probes-fail.out" 2>"$TMPDIR_T/all-probes-fail.err"
grep -q 'WARN: ordinary DNS probes failed for all controls: bad-one.invalid bad-two.invalid' "$TMPDIR_T/all-probes-fail.err" || {
    echo "FAIL: all failed ordinary DNS controls must warn" >&2
    cat "$TMPDIR_T/all-probes-fail.out" >&2
    cat "$TMPDIR_T/all-probes-fail.err" >&2
    exit 1
}

APPLY_MOCKDIR="$TMPDIR_T/apply-mockbin"
install_apply_mocks "$APPLY_MOCKDIR"
APPLY_ROOT="$TMPDIR_T/apply"
make_layout "$APPLY_ROOT"
printf '# Generated by NetworkManager\nnameserver 127.0.0.53\n' >"$APPLY_ROOT/etc/resolv.conf"
APPLY_LOG="$TMPDIR_T/apply.log"
PATH="$APPLY_MOCKDIR:/usr/bin:/bin" \
TAILSCALE_APPLY_LOG="$APPLY_LOG" \
TAILSCALE_SYSTEMD_RESOLVED_ACTIVE=0 \
TAILSCALE_SYSTEMD_RESOLVED_ENABLED=1 \
TAILSCALE_RESOLV_CONF="$APPLY_ROOT/etc/resolv.conf" \
TAILSCALE_STUB_RESOLV_CONF="$APPLY_ROOT/run/systemd/resolve/stub-resolv.conf" \
TAILSCALE_NM_CONFIG_FILE="$APPLY_ROOT/etc/NetworkManager/NetworkManager.conf" \
TAILSCALE_NM_CONFIG_DIR="$APPLY_ROOT/etc/NetworkManager/conf.d" \
TAILSCALE_NM_SYSTEMD_RESOLVED_CONFIG="$APPLY_ROOT/etc/NetworkManager/conf.d/90-pgu-systemd-resolved.conf" \
TAILSCALE_SKIP_LIVE_PROBES=1 \
    "$SCRIPT" --apply >"$TMPDIR_T/apply-inactive.out" 2>"$TMPDIR_T/apply-inactive.err" && {
        echo "FAIL: --apply should abort when systemd-resolved is inactive" >&2
        exit 1
    }
grep -q 'FAIL: systemd-resolved is not active; refusing to repoint' "$TMPDIR_T/apply-inactive.err" || {
    echo "FAIL: inactive systemd-resolved should produce the preflight refusal" >&2
    cat "$TMPDIR_T/apply-inactive.err" >&2
    exit 1
}
if grep -q '^install:' "$APPLY_LOG" || grep -q '^ln:' "$APPLY_LOG"; then
    echo "FAIL: --apply must not mutate after a failed systemd-resolved preflight" >&2
    cat "$APPLY_LOG" >&2
    exit 1
fi
[[ ! -e "$APPLY_ROOT/etc/NetworkManager/conf.d/90-pgu-systemd-resolved.conf" ]] || {
    echo "FAIL: --apply wrote the NM config despite failed preflight" >&2
    exit 1
}

: >"$APPLY_LOG"
rm -f "$APPLY_ROOT/run/systemd/resolve/stub-resolv.conf"
PATH="$APPLY_MOCKDIR:/usr/bin:/bin" \
TAILSCALE_APPLY_LOG="$APPLY_LOG" \
TAILSCALE_SYSTEMD_RESOLVED_ACTIVE=1 \
TAILSCALE_SYSTEMD_RESOLVED_ENABLED=1 \
TAILSCALE_RESOLV_CONF="$APPLY_ROOT/etc/resolv.conf" \
TAILSCALE_STUB_RESOLV_CONF="$APPLY_ROOT/run/systemd/resolve/stub-resolv.conf" \
TAILSCALE_NM_CONFIG_FILE="$APPLY_ROOT/etc/NetworkManager/NetworkManager.conf" \
TAILSCALE_NM_CONFIG_DIR="$APPLY_ROOT/etc/NetworkManager/conf.d" \
TAILSCALE_NM_SYSTEMD_RESOLVED_CONFIG="$APPLY_ROOT/etc/NetworkManager/conf.d/90-pgu-systemd-resolved.conf" \
TAILSCALE_SKIP_LIVE_PROBES=1 \
    "$SCRIPT" --apply >"$TMPDIR_T/apply-missing-stub.out" 2>"$TMPDIR_T/apply-missing-stub.err" && {
        echo "FAIL: --apply should abort when the resolved stub file is absent" >&2
        exit 1
    }
grep -q 'FAIL: .*stub-resolv.conf does not exist; refusing to repoint' "$TMPDIR_T/apply-missing-stub.err" || {
    echo "FAIL: missing stub should produce the preflight refusal" >&2
    cat "$TMPDIR_T/apply-missing-stub.err" >&2
    exit 1
}
if grep -q '^install:' "$APPLY_LOG" || grep -q '^ln:' "$APPLY_LOG"; then
    echo "FAIL: --apply must not mutate after a missing-stub preflight failure" >&2
    cat "$APPLY_LOG" >&2
    exit 1
fi

echo "tailscale_resolved_nm_health_test: ok"
