#!/usr/bin/env python3
"""SYRD-232: a legacy upgrade asks for its desktop policy before it does anything.

Live on mefp. The root-run upgrade completed artifacts, accounts, identities and
the release deploy, closed its journal and reported no remaining Director phase.
The operator then did the documented pane restart: `switchyard stop mefp`
suspended the roles, listener and board, and `switchyard start mefp` brought the
board and listener back and refused to launch a single role:

    switchyard: desktop setup incomplete before launch: Choose a desktop policy
    before launch: --desktop-policy FILE with mode headless or wayland.

The requirement is right -- Wayland access is per tenant and cannot be inferred
from another project -- but the first time anybody was told about it was after a
working tenant had been suspended. `upgrade_project_command` only looked at the
desktop policy when one was supplied or already recorded; a legacy tenant with
neither skipped it silently and was declared prepared.

Everything here drives the real upgrade entry point against a tenant generated by
the real provisioning code. Only host commands, the privileged Wayland install
and its tenant-side verification are simulated.
"""

from __future__ import annotations

import getpass
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "tests") not in sys.path:
    sys.path.insert(0, str(ROOT / "tests"))

from scripts import desktop_access as desktop  # noqa: E402
from scripts import team_launcher as launcher  # noqa: E402
from team_launcher_test_helpers import FakeRunner  # noqa: E402

PROJECT = "mefp"
TENANT = getpass.getuser()
CHECKS = 0


def check(condition: object, message: str) -> None:
    global CHECKS
    assert condition, message
    CHECKS += 1


class Tenant:
    """A legacy tenant: provisioned by the real code, before desktop policies."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.output = root / "provision"
        self.output.mkdir(parents=True)
        plan = launcher.build_plan(project=PROJECT, owner_user=TENANT,
                                   owner_home=root / "home", source_repo=ROOT)
        launcher.write_artifacts(plan, self.output, enable_owner_linger=False)
        self.config_path = launcher.write_new_project_launcher_artifacts(
            plan, self.output, repository=root / "repository", print_func=lambda _text: None)
        raw = json.loads(self.config_path.read_text())
        raw.pop("desktop_access", None)
        self.config_path.write_text(json.dumps(raw))
        (self.output / "desktop-policy.json").unlink(missing_ok=True)
        self.host = FakeRunner()
        self.verified: list[list[str]] = []
        self.installed: list[dict[str, Any]] = []
        self.install_error: Exception | None = None

    @property
    def policy_file(self) -> Path:
        return self.output / "desktop-policy.json"

    def config(self) -> dict[str, Any]:
        return json.loads(self.config_path.read_text())

    def snapshot(self) -> dict[str, tuple[int, bytes]]:
        """Every file under the tenant, with its bytes and its mtime."""
        return {
            str(path.relative_to(self.root)): (path.stat().st_mtime_ns, path.read_bytes())
            for path in sorted(self.root.rglob("*")) if path.is_file()
        }

    def runner(self, args: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        if "verify" in args:
            # The tenant-side check of a Wayland grant, answered as a working one.
            self.verified.append(list(args))
            return subprocess.CompletedProcess(args, 0, json.dumps({
                "WAYLAND_DISPLAY": str(self.root / "gui-runtime/wayland-0"),
                "XDG_RUNTIME_DIR": str(self.root / "tenant-runtime"),
                "DBUS_SESSION_BUS_ADDRESS": "unix:path=" + str(self.root / "tenant-runtime/bus"),
            }), "")
        return self.host(args, **kwargs)

    def install(self, policy: dict[str, Any], **_kwargs: Any) -> None:
        if self.install_error is not None:
            raise self.install_error
        self.installed.append(policy)

    def upgrade(self, *, desktop_policy: Path | None = None, dry_run: bool = False) -> tuple[int, list[str]]:
        said: list[str] = []
        with patch.object(desktop, "install", self.install), patch.object(desktop, "uninstall"):
            rc = launcher.upgrade_project_command(
                launcher.load_project_config(PROJECT, self.config_path),
                config_path=self.config_path, desktop_policy=desktop_policy, dry_run=dry_run,
                source_repo=ROOT, runner=self.runner, print_func=said.append)
        return rc, said

    def start_refusal(self) -> str:
        """What `switchyard start` would say, or '' if it would launch."""
        try:
            launcher.prepare_project_desktop(launcher.load_project_config(PROJECT, self.config_path),
                                             runner=self.runner)
        except SystemExit as exc:
            return str(exc)
        return ""


def wayland_policy(path: Path, *, project: str = PROJECT, tenant: str = TENANT) -> Path:
    path.write_text(json.dumps({
        "mode": "wayland", "gui_user": "root", "tenant_user": tenant, "project": project,
        "wayland_display": "auto",
        "consent": {"approved": True, "by": "root", "at": "2026-09-22T14:30:00Z",
                    "reference": "the operator's recorded approval for this tenant"},
    }))
    return path


def phase_line(said: list[str], name: str) -> str:
    matches = [line for line in said if line.strip().startswith(name)]
    return matches[-1] if matches else ""


def assert_nothing_changed(tenant: Tenant, before: dict[str, tuple[int, bytes]], why: str) -> None:
    after = tenant.snapshot()
    changed = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
    check(not changed, f"{why}, yet files changed: {changed}")
    check(tenant.host.calls == [],
          f"{why}, yet host commands ran -- so a phase started: {tenant.host.calls[:4]}")
    check(tenant.installed == [], f"{why}, yet desktop access was granted: {tenant.installed}")


def test_a_legacy_tenant_is_told_before_any_phase_runs() -> None:
    """The live failure, as a test."""
    with tempfile.TemporaryDirectory(prefix="syrd232-legacy.") as tmp:
        tenant = Tenant(Path(tmp))
        check(tenant.start_refusal(), "the fixture already launches, so it is not a legacy tenant")
        before = tenant.snapshot()
        rc, said = tenant.upgrade()
        text = "\n".join(said)

        check(rc != 0, f"the upgrade reported success for a tenant that cannot start: {rc}")
        check("desktop policy" in text,
              f"the upgrade never mentioned the decision it was missing: {said}")
        # Both choices, each by the command that makes it.
        check(f"switchyard upgrade {PROJECT} --desktop-policy headless" in text,
              f"headless is not offered as a command: {said}")
        check(f"switchyard upgrade {PROJECT} --desktop-policy FILE" in text,
              f"a Wayland policy is not offered as a command: {said}")
        check(repr(TENANT) in text and repr(PROJECT) in text,
              f"the Wayland choice does not say which project and tenant it must name: {said}")
        check("never copied" in text and "never assumed" in text,
              f"nothing says the choice cannot be inferred or borrowed: {said}")
        check("no pane restart" in text,
              f"the operator is not told to hold off the restart: {said}")
        # And it said so before anything else: no phase table, no "prepared".
        check("upgrade phases" not in text, f"phases ran anyway: {said}")
        check("prepared" not in text, f"the tenant was still declared prepared: {said}")
        assert_nothing_changed(tenant, before, "the upgrade stopped before any phase")
        check(tenant.start_refusal(), "a refused upgrade somehow made the tenant launchable")


def test_choosing_headless_is_kept_and_lets_the_tenant_start() -> None:
    with tempfile.TemporaryDirectory(prefix="syrd232-headless.") as tmp:
        tenant = Tenant(Path(tmp))
        rc, said = tenant.upgrade(desktop_policy=Path("headless"))

        check(rc == 0, f"a headless choice did not complete the upgrade: {rc} {said[-3:]}")
        expected = {"mode": "headless", "project": PROJECT, "tenant_user": TENANT}
        check(tenant.config().get("desktop_access") == expected,
              f"the tenant config does not carry the choice: {tenant.config().get('desktop_access')}")
        check(json.loads(tenant.policy_file.read_text()) == expected,
              "the generated desktop-policy.json does not carry the choice")
        check(tenant.installed == [], f"headless granted desktop access: {tenant.installed}")
        check(tenant.start_refusal() == "", f"switchyard start would still refuse: {tenant.start_refusal()}")
        check("ready" in phase_line(said, "desktop") and "headless" in phase_line(said, "desktop"),
              f"the readiness table does not say the tenant can launch: {phase_line(said, 'desktop')!r}")


def test_choosing_an_approved_wayland_policy_installs_and_verifies_it() -> None:
    with tempfile.TemporaryDirectory(prefix="syrd232-wayland.") as tmp:
        tenant = Tenant(Path(tmp))
        chosen = wayland_policy(Path(tmp) / "wayland.json")
        rc, said = tenant.upgrade(desktop_policy=chosen)

        check(rc == 0, f"an approved Wayland policy did not complete the upgrade: {rc} {said[-3:]}")
        check(len(tenant.installed) == 1, f"the scoped access was not installed once: {tenant.installed}")
        check(tenant.installed[0]["project"] == PROJECT and tenant.installed[0]["tenant_user"] == TENANT,
              f"access was installed for somebody else: {tenant.installed[0]}")
        check(tenant.verified, "the grant was installed but never verified from the tenant's side")
        check(TENANT in tenant.verified[0] or tenant.verified[0][0] != "sudo",
              f"verification did not run as the tenant: {tenant.verified[0]}")
        check(tenant.config()["desktop_access"]["mode"] == "wayland",
              f"the choice was not persisted: {tenant.config().get('desktop_access')}")
        check(tenant.start_refusal() == "", f"switchyard start would still refuse: {tenant.start_refusal()}")
        check("wayland" in phase_line(said, "desktop"),
              f"the readiness table does not name the Wayland policy: {phase_line(said, 'desktop')!r}")


def test_another_projects_or_tenants_policy_is_refused_before_anything_changes() -> None:
    """Consent is this tenant's own. Borrowing one is exactly what must not work."""
    for label, kwargs in (("another project", {"project": "otto"}),
                          ("another tenant", {"tenant": "otto-agent"})):
        with tempfile.TemporaryDirectory(prefix="syrd232-mismatch.") as tmp:
            tenant = Tenant(Path(tmp))
            borrowed = wayland_policy(Path(tmp) / "borrowed.json", **kwargs)
            before = tenant.snapshot()
            rc, said = tenant.upgrade(desktop_policy=borrowed)
            text = "\n".join(said)
            check(rc != 0, f"{label}'s policy was accepted for {PROJECT}: {said}")
            check("does not match this tenant" in text,
                  f"the refusal for {label}'s policy does not say why: {said}")
            assert_nothing_changed(tenant, before, f"{label}'s policy was refused")


def test_an_unapproved_wayland_policy_is_refused() -> None:
    with tempfile.TemporaryDirectory(prefix="syrd232-unapproved.") as tmp:
        tenant = Tenant(Path(tmp))
        chosen = wayland_policy(Path(tmp) / "wayland.json")
        raw = json.loads(chosen.read_text())
        raw["consent"]["approved"] = False
        chosen.write_text(json.dumps(raw))
        before = tenant.snapshot()
        rc, said = tenant.upgrade(desktop_policy=chosen)
        check(rc != 0, f"an unapproved grant was accepted: {said}")
        assert_nothing_changed(tenant, before, "an unapproved grant was refused")


def test_a_dry_run_says_the_same_thing_and_does_nothing() -> None:
    with tempfile.TemporaryDirectory(prefix="syrd232-dryrun.") as tmp:
        tenant = Tenant(Path(tmp))
        before = tenant.snapshot()
        rc, said = tenant.upgrade(dry_run=True)
        text = "\n".join(said)
        check(rc != 0, f"a dry run reported that the upgrade would succeed: {rc}")
        check(f"--desktop-policy headless" in text and "--desktop-policy FILE" in text,
              f"the dry run does not name both choices: {said}")
        check("dry run" in text and "would" in text,
              f"the dry run does not say it is describing what apply would do: {said}")
        assert_nothing_changed(tenant, before, "a dry run ran")

        # And a dry run that IS given a choice still grants and writes nothing --
        # while reporting the tenant as ready on that choice, not as missing the
        # policy it was just handed.
        chosen = wayland_policy(Path(tmp) / "wayland.json")
        before = tenant.snapshot()
        rc, said = tenant.upgrade(desktop_policy=chosen, dry_run=True)
        line = phase_line(said, "desktop")
        check("ready" in line and "wayland" in line,
              f"a dry run given a valid policy reports it missing: {line!r}")
        check("would" in line and "records nothing" in line,
              f"the dry run's readiness line claims something was recorded: {line!r}")
        after = tenant.snapshot()
        changed = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
        check(tenant.installed == [], f"a dry run granted desktop access: {tenant.installed}")
        check("desktop_access" not in tenant.config(), "a dry run recorded the policy")
        check(not tenant.policy_file.exists(), "a dry run wrote desktop-policy.json")
        check(not [k for k in changed if "desktop" in k or k.endswith(".json") and "mefp" in k],
              f"a dry run wrote policy state: {changed}")


def test_a_failed_install_leaves_the_tenant_as_it_was() -> None:
    """An apply failure must not touch the board, the listener or a role session."""
    with tempfile.TemporaryDirectory(prefix="syrd232-failed.") as tmp:
        tenant = Tenant(Path(tmp))
        chosen = wayland_policy(Path(tmp) / "wayland.json")
        tenant.install_error = desktop.DesktopAccessError("the GUI session could not be reached")
        before = tenant.snapshot()
        try:
            rc, said = tenant.upgrade(desktop_policy=chosen)
        except SystemExit as exc:
            rc, said = 1, [str(exc)]
        # A SystemExit with a sentence, not a raw exception: anything else
        # escapes the `except SystemExit` above and fails this case outright.
        check(rc != 0, f"a failed install reported success: {said}")
        check("could not be installed" in said[-1] and "Nothing was recorded" in said[-1],
              f"the failure does not say what happened and what did not: {said[-1]}")
        after = tenant.snapshot()
        changed = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
        check(not changed, f"a failed install left files changed: {changed}")
        # Changing something, not asking about it: the upgrade reads the owner's
        # user manager (`systemctl --user is-system-running`) before this step,
        # and a read is not a touch.
        mutating = re.compile(r"systemctl\b.*\b(start|stop|restart|kill|disable|enable|reload)\b"
                              r"|tmux\b.*\b(kill-session|kill-server|new-session|respawn-pane)\b"
                              r"|switchyard\b.*\b(stop|start|teardown)\b")
        touched = [call for call in tenant.host.calls if mutating.search(" ".join(map(str, call)))]
        probes = [call for call in tenant.host.calls if "is-system-running" in " ".join(map(str, call))]
        check(probes, "the manager probe never ran, so this case never reached the desktop step")
        check(touched == [], f"a failed install touched the board, listener or a session: {touched}")
        check("desktop_access" not in tenant.config(), "a failed install recorded the policy anyway")


def test_the_readiness_table_reports_a_missing_policy_as_missing() -> None:
    """The report's own contract, apart from the upgrade that now never reaches it
    without a policy: given none, it says so and names the command."""
    with tempfile.TemporaryDirectory(prefix="syrd232-report.") as tmp:
        tenant = Tenant(Path(tmp))
        config = launcher.load_project_config(PROJECT, tenant.config_path)
        lines = launcher.upgrade_phase_report(
            config, config_path=tenant.config_path,
            cutover=launcher.role_account_cutover(config, runner=tenant.runner), journal={})
        line = phase_line(lines, "desktop")
        check("missing" in line, f"a tenant with no policy is not reported as missing one: {line!r}")
        check(f"--desktop-policy" in line, f"the missing line does not say what to run: {line!r}")


def test_a_rerun_needs_no_second_choice_and_is_idempotent() -> None:
    with tempfile.TemporaryDirectory(prefix="syrd232-rerun.") as tmp:
        tenant = Tenant(Path(tmp))
        rc, _ = tenant.upgrade(desktop_policy=Path("headless"))
        check(rc == 0, "the first, choosing upgrade did not complete")
        recorded = tenant.config()["desktop_access"]
        rc, said = tenant.upgrade()
        check(rc == 0, f"a rerun asked for the choice again: {said[:4]}")
        check(tenant.config()["desktop_access"] == recorded, "a rerun changed the recorded policy")
        check("ready" in phase_line(said, "desktop"), f"a rerun lost its readiness: {phase_line(said, 'desktop')!r}")
        check(tenant.start_refusal() == "", "after a rerun the tenant still cannot start")


def main() -> int:
    for name, case in sorted(globals().items()):
        if name.startswith("test_") and callable(case):
            case()
    print(f"team_launcher_legacy_desktop_policy_upgrade_test: ok ({CHECKS} checks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
